name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Andy!"
      - name: Current Date
        run: date
      - run: ls -l
