name: Deployment Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    permissions:
      deployments: write
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Netlify
        run: npm install netlify-cli@17.25.0 -g
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
        #   - name: E2E Cypress Test - Needs to be fixed
        #     uses: cypress-io/github-action@v6
        #     with:
        #       command: npm run test:e2e
        #       start: npm run dev
        #       wait-on: http://localhost:5173/
      - name: Deploy
        id: netlify_deploy
        if: ${{github.event_name == 'push'}}
        run: |
          prod_flag="--prod"
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            $prod_flag \
            --json \
            > deploy_output.json
      - name: URL Preview
        id: url_preview
        if: ${{github.event_name == 'push'}}
        run: |
          NETLIFY_PREVIEW_URL=$(jq -r '.deploy_url' deploy_output.json)
          echo "NETLIFY_PREVIEW_URL=$NETLIFY_PREVIEW_URL" >> "GITHUB_OUTPUT"
      - name: Write Preview URL
        uses: actions/github-script@v7
        if: ${{github.event_name == 'push'}}
        env:
          NETLIFY_PREVIEW_URL: ${{steps.url_preview.outputs.NETLIFY_PREVIEW_URL}}
        with:
          script: |
            async function comment() {
                const result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    commit_sha: context.sha,
                })

                const issueNumber = result.data[0].number

                if(!issueNumber) {
                    console.log(`No PR found for commit ${context.sha}`)
                }

                await github.rest.issues.createComment({
                    issue_number: issueNumber,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: `Preview URL: ${process.env.NETLIFY_PREVIEW_URL}`
                })
            }

            comment()
